name: insporation
description: A native diaspora* client
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cached_network_image: ^3.0.0
  carousel_slider: ^4.0.0-nullsafety.0
  catcher: ^0.6.3
  expandable_widget: ^2.0.0-nullsafety
  flutter_app_badger: ^1.2.0
  flutter_html: ^2.0.0-nullsafety.0
  flutter_slidable: ^0.6.0
  geojson: ^0.10.0
  gesture_zoom_box:
    git:
      url: https://github.com/jhass/gesture_zoom_box.git
      ref: nullsafety
      path: package_src
  http: ^0.13.0
  image_crop:
    git:
      url: https://github.com/vmeretin/image_crop.git
      ref: null-safety
  image_picker: ^0.7.0
  intl: ^0.17.0
  markdown: ^4.0.0
  provider: ^5.0.0
  quiver: ^3.0.0
  share: ^2.0.0
  shared_preferences: ^2.0.5
  timeago: ^3.0.2
  transparent_image: ^2.0.0
  url_launcher: ^6.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  latlong:
    git: https://github.com/SametSahin10/dart-latlong.git

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/icons/
