name: insporation
description: A native diaspora* client
version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^4.0.1
  shared_preferences: ^0.5.6+1
  http: ^0.12.0+4
  timeago: ^2.0.24
  transparent_image: ^1.0.0
  markdown: ^2.1.3
  flutter_html: ^1.0.0-pre.1
  url_launcher: ^5.4.1
  carousel_slider: ^2.3.1
  cached_network_image: ^2.0.0
  gesture_zoom_box: ^0.0.2
  flutter_slidable: ^0.5.4
  intl: ^0.16.0
  intl_translation: ^0.17.9
  image_picker: ^0.6.3+1
  image_crop: ^0.3.2
  flutter_app_badger: ^1.1.2
  geojson: ^0.9.1
  quiver: ^2.0.5
  expandable_widget: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
