# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    if is_ci
      increment_build_number(build_number: ENV["GITHUB_RUN_NUMBER"] || "1")
      create_keychain(
        name: "fastlane_ci",
        password: "ci_keychain",
        default_keychain: true,
        unlock: true,
        timeout: 3600,
        lock_when_sleeps: false
      )
      match(
        git_url: "git@github.com:jhass/insporation-certificates.git",
        type: "appstore",
        keychain_name: 'fastlane_ci',
        keychain_password: 'ci_keychain',
        readonly: true
      )
    else
      # please run bundle exec fastlane match appstore manually
    end

    build_app(
      workspace: "Runner.xcworkspace",
      scheme: "Runner",
      export_method: "app-store"
    )

    upload_to_testflight(
      distribute_external: true,
      # TODO: CI: move automatic release step into job running prior this
      # and fetch changelog from the release notes
      changelog: "Latest nightly build changes",
      reject_build_waiting_for_review: true
    )
  end
end
