# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

  desc "Push a new beta build to TestFlight"
  lane :beta do
    increment_build_number(build_number: ENV["GITHUB_RUN_NUMBER"] || "1")
    create_keychain(
      name: "fastlane_ci",
      password: "ci_keychain",
      default_keychain: true,
      unlock: true,
      timeout: 3600,
      add_to_search_list: true,
    )
    match(
      profile_name: "match_profile",
      git_url: "git@github.com:jhass/insporation-certificates.git",
      type: "development",
      keychain_name: 'fastlane_ci',
      keychain_password: 'ci_keychain'
      readonly: true
    )
    build_app(
      workspace: "Runner.xcworkspace",
      scheme: "Runner",
      export_method: "app-store",
      export_options: {
        provisioningProfiles: {
          "eu.jhass.insporation" => "match_profile",
        }
      }
    )
    upload_to_testflight(skip_waiting_for_build_processing: true)
  end
end
