name: CI

# Until there are actual tests, we just smoke test by building the app

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-android:
    runs-on: ubuntu-latest
    container:
      image: circleci/android:api-28-node
      options: -u root
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v1
    - name: Build
      run: flutter build apk --debug
  build-ios:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v1
    - name: Build
      run: flutter build ios --debug --no-codesign
