name: CI

# Until there are actual tests, we just smoke test by building the app

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-android:
    runs-on: ubuntu-latest
    container:
      image: circleci/android:api-30-node
      options: -u root
    steps:
    - name: "Install SDK 32"
      run: sdkmanager "build-tools;32.0.0"
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.7'
    - name: Build
      run: flutter build apk --debug
  build-ios:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.7'
    - name: Build
      run: flutter build ios --debug --no-codesign
