name: CI

# Until there are actual tests, we just smoke test by building the app

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  build-android:
    runs-on: ubuntu-latest
    container:
      image: cimg/android:2026.03.1-node
      options: -u root
    steps:
    - name: "Install SDK 36 build tools"
      run: sdkmanager "build-tools;36.0.0"
    - uses: actions/checkout@v7
    - uses: subosito/flutter-action@v2
      id: flutter-action
      with:
        flutter-version: '3.41.x'
        channel: stable
    - name: Workaround flutter directory permissions
      run: |-
        git config --global --add safe.directory ${{ steps.flutter-action.outputs.CACHE-PATH }}
        git config --global --add safe.directory ${{ steps.flutter-action.outputs.CACHE-PATH }}/flutter
        git config --global --add safe.directory $(pwd)
    - name: Build
      run: flutter build apk --debug
  build-ios:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v7
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: latest-stable
    - name: Install iOS SDK
      run: |
        xcrun simctl list > /dev/null # https://github.com/actions/runner-images/issues/13459
        xcodebuild -downloadPlatform iOS
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.41.x'
        channel: stable
    - name: Build
      run: flutter build ios --debug --no-codesign
