name: Nightly trigger

on:
  schedule:
    - cron: '0 4 * * *'

jobs:
  trigger:
    runs-on: ubuntu-latest
    environment: release-build
    steps:
    - uses: actions/checkout@v2
    - run: |
        git fetch --depth=1 --no-tags origin +refs/tags/nightly:refs/tags/nightly
        [ "$(git show-ref -s --head HEAD)" != "$(git show-ref -s nightly)" ] &&
          script/trigger-nightly || echo "no changes"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_AUTOMATION_TOKEN }}
